server:
  port: 8084

myRoom:
  platformFeePercentage: 2
  frontendUrl: http://localhost:3000

# Stripe API
stripe:
  api:
    secret-key: sk_test_51SHdxkRzecus95EIBT3TWygEqwkDd40RD0audbYpRscNTYbEJUDDs4gzZlsnl85VVu7NrliR0aaXVCjEHUHBJH9F00n0SE568w
  endpointSecret: whsec_83a80ba1ef4f5fb96969b7ea768924c514a950bdf60fbfc2923b3d5d9c0c9a9b


services:
  booking-service:
    id: BOOKING-SERVICE
    v1:
      api: /api/v1/booking-service
      name: BOOKING-SERVICE_V1

  payment-service:
    id: PAYMENT-SERVICE
    v1:
      api: /api/v1/payment-service
      name: PAYMENT-SERVICE_V1

  organization-pay:
    id: ORGANIZATION-PAY-SERVICE
    v1:
      api: /api/v1/organizationpay
      name: ORGANIZATION-PAY-SERVICE_V1

  room-service:
    id: ROOM-SERVICE
    v1:
      api: /api/v1/room-service
      name: ROOM-SERVICE_V1

spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/myroom
    username: root
    password: leminhduc472005

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    advertised:
      host:
        name: localhost

  main:
    allow-circular-references: true


# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka