global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
        - 'host.docker.internal:8761'  
        - 'host.docker.internal:9091'  
        - 'host.docker.internal:8080'  
        - 'host.docker.internal:8081'  
        - 'host.docker.internal:8082'  
        - 'host.docker.internal:8083'  
        - 'host.docker.internal:8084'  
        - 'host.docker.internal:8087'  

  - job_name: 'nodejs_microservices'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - 'host.docker.internal:8085'  
        - 'host.docker.internal:8086'  
        - 'host.docker.internal:8089'  
        - 'host.docker.internal:8088'  